{"variants":[{"paths":["\/documentation\/authfoundation\/oauth2error\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/LocalizedError-Implementations","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No overview available."}],"kind":"article","metadata":{"modules":[{"name":"AuthFoundation"}],"role":"collectionGroup","title":"LocalizedError Implementations"},"hierarchy":{"paths":[["doc:\/\/AuthFoundation\/documentation\/AuthFoundation","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/errorDescription-46l3j","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/errorDescription-4kk0u","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/failureReason","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/helpAnchor","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/recoverySuggestion"],"generated":true}],"references":{"doc://AuthFoundation/documentation/AuthFoundation":{"role":"collection","title":"AuthFoundation","abstract":[{"type":"text","text":"Library that provides foundational features used by Oktaâ€™s authentication libraries, as well as APIs used to work with tokens and user credentials."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/failureReason":{"role":"symbol","title":"failureReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/failureReason","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/failurereason"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/errorDescription-4kk0u":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/errorDescription-4kk0u","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/errordescription-4kk0u"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/helpAnchor":{"role":"symbol","title":"helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/helpAnchor","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/helpanchor"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/errorDescription-46l3j":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/errorDescription-46l3j","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/errordescription-46l3j"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error":{"role":"symbol","title":"OAuth2Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2Error"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuth2Error"}],"url":"\/documentation\/authfoundation\/oauth2error"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/recoverySuggestion":{"role":"symbol","title":"recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/recoverySuggestion","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/recoverysuggestion"}}}